#
# Audio Dsp Preprocess
# Author linxsh
#
# Makefile: Audio Dsp Top Makefile
#
#----------------------------------------------------------------------------------
# Just run 'make menuconfig', configure stuff, then run 'make'.
# You shouldn't need to mess with anything beyond this point...
#----------------------------------------------------------------------------------

###################################################################################
#
# You should probably leave this stuff alone unless you know
# what you are doing.
#
###################################################################################

.PHONY: menuconfig post_config autoconf

all: build

# absolute path
CURDIR          := $(shell pwd)
Q               := @
obj             := $(CURDIR)/scripts/kconfig
SUBDIR          := $(obj)
CONFIG_KCONFIG  := Kconfig

ifeq ($(quiet),silent_)
silent := -s
endif

menuconfig : $(obj)/mconf $(obj)/conf
	$(Q)$< $(CONFIG_KCONFIG)
	@scripts/autoconf.sh > /dev/null
	@scripts/config_parse.sh > /dev/null

$(obj)/mconf:
	$(Q)$(MAKE) -C $(SUBDIR) prepare
	$(Q)$(MAKE) -C $(SUBDIR)

$(obj)/conf:
	$(Q)$(MAKE) -C $(SUBDIR) prepare
	$(Q)$(MAKE) -C $(SUBDIR)

autoconf:
	@scripts/autoconf.sh > /dev/null

post_config:
	@scripts/config_parse.sh > /dev/null


###################################################################################
.PHONY: clean distclean help export

build: .config prepare output/dsp.elf output/mcu.elf output/vsp.ko checkbin

.config:
	@make menuconfig

prepare: autoconf post_config
	@mkdir -p output

output/dsp.elf: prepare
	@echo [===================== Build DSP Firmware =====================]
	$(Q)make -C dsp

output/mcu.elf: output/dsp.elf
	@echo [===================== Build MCU Firmware =====================]
	$(Q)make -C mcu

output/vsp.ko: output/dsp.elf
	@echo [============= Build CPU Driver, Library, and Tools ===========]
	$(Q)make -C cpu

checkbin:
	@echo [======================== List Output =========================]
	@-ls -l output/*

clean:
	@-make -C dsp clean
	@-make -C mcu clean
	@-make -C cpu clean
	@-rm include/autoconf.h
	@-rm -rf output
	@echo [Clean all]

distclean: clean
	@-make -C $(SUBDIR) clean
	@-find . -name *.o | xargs rm
	@-find . -name *.d | xargs rm
	@-rm -f .config .config.old
	@-rm -f include/autogenerated_config.h
	@-rm -f include/autoconf.h

publish: build
	@echo [======================== VSP Publish =========================]
	@scripts/publish.sh

help:
	@echo 'Cleaning:'
	@echo '  clean                  - delete all files created by build'
	@echo '  distclean              - delete all non-source files (including .config)'
	@echo
	@echo 'Configuration:'
	@echo '  menuconfig             - interactive curses-based configurator'
	@echo
	@echo 'Compiled:'
	@echo '  bin                    - compiled binary file'
	@echo
	@echo 'Release:'
	@echo '  sdk                    - build a SDK package'
	@echo

###################################################################################
# Some help phony
.PHONY: dsp mcu cpu bin

dsp: prepare
	$(Q)make -C dsp

mcu: prepare
	$(Q)make -C mcu

cpu: prepare
	$(Q)make -C cpu

bin:
	$(Q)make -C bin
