include ../.config
include resolver.mak
include compiler.mak

prepare:
	@echo "\033[31;31mVersion:  "$(CONFIG_VERSION)"\033[0m"
	@echo "\033[31;31mPlatform: "$(PLATFORM)"\033[0m"
	@echo "\033[31;31mDecoder:  "$(DECODER)"\033[0m"
	@echo "\033[31;31mEncoder:  "$(ENCODER)"\033[0m"

link:
	@echo
